server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: socials-config-repo
  profiles:
    active: native
  application:
    name: socials-configserver
